package pojo;
// Generated Jun 11, 2021 5:19:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Giaovu generated by hbm2java
 */
public class Giaovu  implements java.io.Serializable {


     private String maGv;
     private String password;
     private String tenGv;
     private Date namSinh;
     private String diaChi;
     private String sdt;

    public Giaovu() {
    }

	
    public Giaovu(String maGv, String tenGv) {
        this.maGv = maGv;
        this.tenGv = tenGv;
    }
    public Giaovu(String maGv, String password, String tenGv, Date namSinh, String diaChi, String sdt) {
       this.maGv = maGv;
       this.password = password;
       this.tenGv = tenGv;
       this.namSinh = namSinh;
       this.diaChi = diaChi;
       this.sdt = sdt;
    }
   
    public String getMaGv() {
        return this.maGv;
    }
    
    public void setMaGv(String maGv) {
        this.maGv = maGv;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTenGv() {
        return this.tenGv;
    }
    
    public void setTenGv(String tenGv) {
        this.tenGv = tenGv;
    }
    public Date getNamSinh() {
        return this.namSinh;
    }
    
    public void setNamSinh(Date namSinh) {
        this.namSinh = namSinh;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }




}


