package pojo;
// Generated Jun 8, 2021 6:18:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Giaovu generated by hbm2java
 */
public class Giaovu  implements java.io.Serializable {


     private String maGv;
     private String tenGv;
     private Date namSinh;
     private String diaChi;
     private String sdt;
     private Set quanlygiaovus = new HashSet(0);

    public Giaovu() {
    }

	
    public Giaovu(String maGv, String tenGv) {
        this.maGv = maGv;
        this.tenGv = tenGv;
    }
    public Giaovu(String maGv, String tenGv, Date namSinh, String diaChi, String sdt, Set quanlygiaovus) {
       this.maGv = maGv;
       this.tenGv = tenGv;
       this.namSinh = namSinh;
       this.diaChi = diaChi;
       this.sdt = sdt;
       this.quanlygiaovus = quanlygiaovus;
    }
   
    public String getMaGv() {
        return this.maGv;
    }
    
    public void setMaGv(String maGv) {
        this.maGv = maGv;
    }
    public String getTenGv() {
        return this.tenGv;
    }
    
    public void setTenGv(String tenGv) {
        this.tenGv = tenGv;
    }
    public Date getNamSinh() {
        return this.namSinh;
    }
    
    public void setNamSinh(Date namSinh) {
        this.namSinh = namSinh;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public Set getQuanlygiaovus() {
        return this.quanlygiaovus;
    }
    
    public void setQuanlygiaovus(Set quanlygiaovus) {
        this.quanlygiaovus = quanlygiaovus;
    }




}


