package pojo;
// Generated Jun 8, 2021 6:18:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hocky generated by hbm2java
 */
public class Hocky  implements java.io.Serializable {


     private HockyId id;
     private Date ngayBd;
     private Date ngayKt;
     private Boolean hocKyHienTai;
     private Set hocphans = new HashSet(0);

    public Hocky() {
    }

	
    public Hocky(HockyId id) {
        this.id = id;
    }
    public Hocky(HockyId id, Date ngayBd, Date ngayKt, Boolean hocKyHienTai, Set hocphans) {
       this.id = id;
       this.ngayBd = ngayBd;
       this.ngayKt = ngayKt;
       this.hocKyHienTai = hocKyHienTai;
       this.hocphans = hocphans;
    }
   
    public HockyId getId() {
        return this.id;
    }
    
    public void setId(HockyId id) {
        this.id = id;
    }
    public Date getNgayBd() {
        return this.ngayBd;
    }
    
    public void setNgayBd(Date ngayBd) {
        this.ngayBd = ngayBd;
    }
    public Date getNgayKt() {
        return this.ngayKt;
    }
    
    public void setNgayKt(Date ngayKt) {
        this.ngayKt = ngayKt;
    }
    public Boolean getHocKyHienTai() {
        return this.hocKyHienTai;
    }
    
    public void setHocKyHienTai(Boolean hocKyHienTai) {
        this.hocKyHienTai = hocKyHienTai;
    }
    public Set getHocphans() {
        return this.hocphans;
    }
    
    public void setHocphans(Set hocphans) {
        this.hocphans = hocphans;
    }




}


