package pojo;
// Generated Jun 8, 2021 6:18:02 PM by Hibernate Tools 4.3.1



/**
 * HockyId generated by hbm2java
 */
public class HockyId  implements java.io.Serializable {


     private String tenHk;
     private String namHoc;

    public HockyId() {
    }

    public HockyId(String tenHk, String namHoc) {
       this.tenHk = tenHk;
       this.namHoc = namHoc;
    }
   
    public String getTenHk() {
        return this.tenHk;
    }
    
    public void setTenHk(String tenHk) {
        this.tenHk = tenHk;
    }
    public String getNamHoc() {
        return this.namHoc;
    }
    
    public void setNamHoc(String namHoc) {
        this.namHoc = namHoc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HockyId) ) return false;
		 HockyId castOther = ( HockyId ) other; 
         
		 return ( (this.getTenHk()==castOther.getTenHk()) || ( this.getTenHk()!=null && castOther.getTenHk()!=null && this.getTenHk().equals(castOther.getTenHk()) ) )
 && ( (this.getNamHoc()==castOther.getNamHoc()) || ( this.getNamHoc()!=null && castOther.getNamHoc()!=null && this.getNamHoc().equals(castOther.getNamHoc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTenHk() == null ? 0 : this.getTenHk().hashCode() );
         result = 37 * result + ( getNamHoc() == null ? 0 : this.getNamHoc().hashCode() );
         return result;
   }   


}


