package pojo;
// Generated Jun 8, 2021 6:18:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hocphan generated by hbm2java
 */
public class Hocphan  implements java.io.Serializable {


     private HocphanId id;
     private Hocky hocky;
     private Monhoc monhoc;
     private String giaoVienLt;
     private String ca;
     private String thu;
     private String phong;
     private Integer soLuongToiDa;
     private Set dangkies = new HashSet(0);
     private Set lops = new HashSet(0);

    public Hocphan() {
    }

	
    public Hocphan(HocphanId id, Hocky hocky) {
        this.id = id;
        this.hocky = hocky;
    }
    public Hocphan(HocphanId id, Hocky hocky, Monhoc monhoc, String giaoVienLt, String ca, String thu, String phong, Integer soLuongToiDa, Set dangkies, Set lops) {
       this.id = id;
       this.hocky = hocky;
       this.monhoc = monhoc;
       this.giaoVienLt = giaoVienLt;
       this.ca = ca;
       this.thu = thu;
       this.phong = phong;
       this.soLuongToiDa = soLuongToiDa;
       this.dangkies = dangkies;
       this.lops = lops;
    }
   
    public HocphanId getId() {
        return this.id;
    }
    
    public void setId(HocphanId id) {
        this.id = id;
    }
    public Hocky getHocky() {
        return this.hocky;
    }
    
    public void setHocky(Hocky hocky) {
        this.hocky = hocky;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public String getGiaoVienLt() {
        return this.giaoVienLt;
    }
    
    public void setGiaoVienLt(String giaoVienLt) {
        this.giaoVienLt = giaoVienLt;
    }
    public String getCa() {
        return this.ca;
    }
    
    public void setCa(String ca) {
        this.ca = ca;
    }
    public String getThu() {
        return this.thu;
    }
    
    public void setThu(String thu) {
        this.thu = thu;
    }
    public String getPhong() {
        return this.phong;
    }
    
    public void setPhong(String phong) {
        this.phong = phong;
    }
    public Integer getSoLuongToiDa() {
        return this.soLuongToiDa;
    }
    
    public void setSoLuongToiDa(Integer soLuongToiDa) {
        this.soLuongToiDa = soLuongToiDa;
    }
    public Set getDangkies() {
        return this.dangkies;
    }
    
    public void setDangkies(Set dangkies) {
        this.dangkies = dangkies;
    }
    public Set getLops() {
        return this.lops;
    }
    
    public void setLops(Set lops) {
        this.lops = lops;
    }




}


