package pojo;
// Generated Jun 8, 2021 6:18:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Quanlygiaovu generated by hbm2java
 */
public class Quanlygiaovu  implements java.io.Serializable {


     private Integer id;
     private Giaovu giaovu;
     private String password;
     private Date lichSu;

    public Quanlygiaovu() {
    }

	
    public Quanlygiaovu(String password) {
        this.password = password;
    }
    public Quanlygiaovu(Giaovu giaovu, String password, Date lichSu) {
       this.giaovu = giaovu;
       this.password = password;
       this.lichSu = lichSu;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Giaovu getGiaovu() {
        return this.giaovu;
    }
    
    public void setGiaovu(Giaovu giaovu) {
        this.giaovu = giaovu;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLichSu() {
        return this.lichSu;
    }
    
    public void setLichSu(Date lichSu) {
        this.lichSu = lichSu;
    }




}


